spring.application.name=Ecommerce_Lepicerie
spring.datasource.url=jdbc:mariadb://172.16.0.210:3306/db_epicerie?createDatabaseIfNotExist=true
spring.datasource.username=epousse
spring.datasource.password=Umyafo34
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop